name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.11.0"
          rebar3-version: "3"
          # elixir-version: "1"
      - run: gleam deps download
      - run: gleam test
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          TEST_USER_PUUID: ${{ secrets.TEST_USER_PUUID }}
          TEST_USER_GAME_NAME: ${{ secrets.TEST_USER_GAME_NAME }}
          TEST_USER_TAG_LINE: ${{ secrets.TEST_USER_TAG_LINE }}
          
      - run: gleam format --check src test
